name: Deploy to GitHub Pages (docs folder)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Move build to docs folder
        run: |
          rm -rf docs
          mv dist docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Deploy site to docs" || echo "No changes to commit"
          git push
